### ISSUE TITLE
read fstab via code-bus bucket to avoid github authentication

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-content-bus#18]
private github repositories can't be accessed so it's better to read the fstab from the code-bus bucket.

**Comment by dominique-pfister** [comment]
I'm a bit confused: there is a PR for propagating the `x-github-token`, there is an issue to read the content from sources (to avoid reading the `fstab`) and there is this issue to read the `fstab` - aren't these all intervowen?

**Comment by tripodsan** [comment]
yes. the PR is just for making it work now.

this issue is needed for #19
