### ISSUE TITLE
read content direct from sources instead via content-proxy service

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-content-bus#19]
the content-proxy needs to read the fstab from the github repository, which is a problem for private repository.
so better to read the fstab via code-bus (see #18) and then read the content from the source directly.

**Comment by tripodsan** [comment]
@dominique-pfister to start with, we could just re-use the respective handlers of content-proxy: `onedrive.js` and `google.js`. 

alternatively, we could modify content-proxy to accept a `mountpoint` and bypass fstab resolution: `mpType=onedrive&mpRelPath=/index.md&mpURL=https://sharepoint....`

**Comment by dominique-pfister** [comment]
> the content-proxy needs to read the fstab from the github repository, which is a problem for private repository.
so better to read the fstab via code-bus (see #18) and then read the content from the source directly.

Sorry, can you be a bit more precise? Is that a) `content-proxy.js` in `helix-content-bus` or b) `helix-content-proxy`?

If a), `content-proxy.js` does not read fstab, it is a **required** config of `helix-content-bus`. IIUC, you want to make it **optional** and fall back to parameters mpXXX. At the same time, you no longer want to invoke `helix-content-proxy`, but copy the required functionality contained in `onedrive.js` and `google.js` into this service, right?

**Comment by tripodsan** [comment]
I mean the content-proxy service.

two options:

a) read directly from the sources, but reuse the code in @adobe/helix-content-proxy (import/require)
b) still use the content-proxy service, but send along the mountpoint, so that the content-proxy service does not need to read github.

**Comment by tripodsan** [comment]
see https://github.com/adobe/helix-content-proxy/issues/410
