### ISSUE TITLE
Purge live cache on content update

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-content-bus#76]
When adding/updating a file in `live`, its corresponding `.live` URL remains cached with the old version.

Workaround: manual `curl -X PURGE <url>`

**Comment by tripodsan** [comment]
this is done in helix-admin:
https://github.com/adobe/helix-admin/blob/33aa67038c17dda4e239988a6157fb5b81db2af9/src/publish.js#L45

the `preview` action doesn't need to update the live cache.

**Comment by kptdobe** [comment]
Sorry, I rephrased my initial comment and changed the label to bug then. We thought it was not implemented because when publishing a page, the `hlx.live` page requires a manual purge to be updated. Thus the `purge` does not work. We might move this issue in `helix-admin` then.

**Comment by kptdobe** [comment]
Creating an issue in helix-admin.
